import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-[#5295d2] from-10% via-[#52b5d2] via-30% to-[#54d6c6] to-90%">
        {/*Header*/}
        <Header />

        {children}
        {/*Toaster*/}
        </body>
    </html>
  );
}
